"use client";

import { useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  CheckCircle2,
  GitPullRequest,
  GitBranch,
  GitCommit,
  FileCode,
  Loader2,
  Sparkles,
  AlertCircle,
  Edit3,
} from "lucide-react";
import { Fix } from "@/app/dashboard/types";
import axios from "axios";

interface CreatePRDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  repoUrl: string;
  branchName: string;
  baseBranch?: string;
  commitHash?: string;
  fixes: Fix[];
  timeTaken?: number;
  teamName?: string;
  teamLeaderName?: string;
  githubToken?: string;
  onPRCreated: (prUrl: string, repoName: string) => void;
}

export function CreatePRDialog({
  open,
  onOpenChange,
  repoUrl,
  branchName,
  baseBranch = "main",
  commitHash,
  fixes,
  timeTaken,
  teamName,
  teamLeaderName,
  githubToken,
  onPRCreated,
}: CreatePRDialogProps) {
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isEditing, setIsEditing] = useState(false);

  const fixedFixes = fixes.filter((f) => f.status === "fixed");
  const fixedCount = fixedFixes.length;

  // Parse repo full name from URL
  const getRepoFullName = (url: string) => {
    const cleanUrl = url.replace(/\.git$/, "").replace(/\/$/, "");
    const parts = cleanUrl.split("/");
    return `${parts[parts.length - 2]}/${parts[parts.length - 1]}`;
  };

  const repoFullName = getRepoFullName(repoUrl);

  // Generate default PR title
  const defaultTitle = fixedFixes.length > 0 && fixedFixes[0].commit_message
    ? `AI Fix: ${fixedFixes[0].commit_message.split(":").pop()?.trim().slice(0, 50)}...`
    : `AI Fix: Automated bug fixes for ${repoFullName}`;

  // Generate default PR body
  const generatePRBody = () => {
    let body = "## AI Fix Summary\n\n";
    body += "The following issues were identified and fixed by the GreenBranch AI agent:\n\n";

    fixedFixes.forEach((fix, idx) => {
      body += `### ${idx + 1}. Fix in \`${fix.file}\`\n`;
      if (fix.explanation) {
        if (fix.explanation.root_cause) {
          body += `- **Root Cause:** ${fix.explanation.root_cause}\n`;
        }
        if (fix.explanation.changes_made) {
          body += `- **Changes Made:** ${fix.explanation.changes_made}\n`;
        }
        if (fix.explanation.impact) {
          body += `- **Impact:** ${fix.explanation.impact}\n`;
        }
      } else if (fix.description) {
        body += `- ${fix.description}\n`;
      }
      body += "\n";
    });

    if (teamName || teamLeaderName) {
      body += "---\n";
      body += `**Team:** ${teamName || "N/A"}\n`;
      body += `**Team Leader:** ${teamLeaderName || "N/A"}\n\n`;
    }

    body += "---\n*Generated by GreenBranch AI*";
    return body;
  };

  const [prTitle, setPrTitle] = useState(defaultTitle);
  const [prBody, setPrBody] = useState(generatePRBody());

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.round(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  const handleCreatePR = async () => {
    if (!githubToken) {
      setError("GitHub token not available. Please sign in with GitHub.");
      return;
    }

    setIsCreating(true);
    setError(null);

    try {
      const agentUrl = process.env.NEXT_PUBLIC_EC2_AGENT_URL;

      const response = await axios.post(`${agentUrl}/api/v1/pr`, {
        repo_full_name: repoFullName,
        branch_name: branchName,
        base_branch: baseBranch,
        title: prTitle,
        body: prBody,
        github_token: githubToken,
      });

      if (response.data.success) {
        onPRCreated(response.data.pr_url, repoFullName);
        onOpenChange(false);
      } else {
        setError(response.data.message || "Failed to create PR");
      }
    } catch (err: any) {
      const message = err.response?.data?.detail || err.response?.data?.message || err.message;
      setError(`Failed to create PR: ${message}`);
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent className="sm:max-w-2xl border-primary/20 bg-card overflow-hidden max-h-[90vh] overflow-y-auto">
        {/* Decorative background */}
        <div className="absolute -top-20 -left-20 h-40 w-40 rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute -bottom-20 -right-20 h-40 w-40 rounded-full bg-primary/10 blur-3xl" />

        <AlertDialogHeader className="relative">
          {/* Success Icon */}
          <div className="flex justify-center mb-4">
            <div className="relative">
              <div className="flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-primary/20 to-primary/5 ring-1 ring-primary/20">
                <CheckCircle2 className="h-10 w-10 text-primary" />
              </div>
              <div className="absolute -right-1 -bottom-1 flex h-8 w-8 items-center justify-center rounded-full bg-background ring-4 ring-background">
                <GitPullRequest className="h-5 w-5 text-primary" />
              </div>
            </div>
          </div>

          <AlertDialogTitle className="text-2xl text-center">
            All Tests Passed!
          </AlertDialogTitle>
          <AlertDialogDescription className="text-center text-base">
            Your code fixes are ready. Create a Pull Request to merge the changes.
          </AlertDialogDescription>
        </AlertDialogHeader>

        {/* Content Section */}
        <div className="space-y-4 py-4">
          {/* Quick Stats */}
          <div className="grid grid-cols-3 gap-3">
            <div className="rounded-lg border border-border/50 bg-secondary/20 p-3 text-center">
              <div className="flex justify-center mb-1.5">
                <FileCode className="h-4 w-4 text-primary" />
              </div>
              <p className="text-lg font-bold text-foreground">{fixedCount}</p>
              <p className="text-xs text-muted-foreground">Files Fixed</p>
            </div>
            <div className="rounded-lg border border-border/50 bg-secondary/20 p-3 text-center">
              <div className="flex justify-center mb-1.5">
                <GitCommit className="h-4 w-4 text-purple-500" />
              </div>
              <p className="text-lg font-bold text-foreground">{fixedCount}</p>
              <p className="text-xs text-muted-foreground">Commits</p>
            </div>
            <div className="rounded-lg border border-border/50 bg-secondary/20 p-3 text-center">
              <div className="flex justify-center mb-1.5">
                <Sparkles className="h-4 w-4 text-yellow-500" />
              </div>
              <p className="text-lg font-bold text-foreground">
                {timeTaken ? formatTime(timeTaken) : "--"}
              </p>
              <p className="text-xs text-muted-foreground">Time Taken</p>
            </div>
          </div>

          {/* Branch Info */}
          <div className="rounded-xl border border-border/50 bg-secondary/20 p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <GitBranch className="h-4 w-4 text-primary" />
                <span className="text-sm text-muted-foreground">Branch:</span>
              </div>
              <code className="text-sm font-mono text-primary">{branchName}</code>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <GitBranch className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm text-muted-foreground">Target:</span>
              </div>
              <code className="text-sm font-mono text-foreground">{baseBranch}</code>
            </div>
            {commitHash && (
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <GitCommit className="h-4 w-4 text-purple-500" />
                  <span className="text-sm text-muted-foreground">Commit:</span>
                </div>
                <code className="text-sm font-mono text-foreground">{commitHash.slice(0, 8)}</code>
              </div>
            )}
          </div>

          {/* PR Title & Body Editor */}
          <div className="rounded-xl border border-border/50 bg-secondary/20 p-4 space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Pull Request Details
              </p>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsEditing(!isEditing)}
                className="h-7 gap-1.5 text-xs"
              >
                <Edit3 className="h-3 w-3" />
                {isEditing ? "Done" : "Edit"}
              </Button>
            </div>

            {isEditing ? (
              <div className="space-y-3">
                <div className="space-y-1.5">
                  <label className="text-xs font-medium text-foreground">PR Title</label>
                  <Input
                    value={prTitle}
                    onChange={(e) => setPrTitle(e.target.value)}
                    className="bg-background/50 text-sm"
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-medium text-foreground">PR Description</label>
                  <Textarea
                    value={prBody}
                    onChange={(e) => setPrBody(e.target.value)}
                    className="bg-background/50 text-sm min-h-[150px] font-mono"
                  />
                </div>
              </div>
            ) : (
              <div className="space-y-2">
                <div className="rounded-lg bg-background/50 px-3 py-2">
                  <p className="text-xs text-muted-foreground mb-1">Title</p>
                  <p className="text-sm font-medium text-foreground">{prTitle}</p>
                </div>
                <div className="rounded-lg bg-background/50 px-3 py-2 max-h-32 overflow-y-auto">
                  <p className="text-xs text-muted-foreground mb-1">Description Preview</p>
                  <pre className="text-xs text-foreground whitespace-pre-wrap font-mono">{prBody.slice(0, 300)}...</pre>
                </div>
              </div>
            )}
          </div>

          {/* Changes Summary */}
          <div className="rounded-xl border border-border/50 bg-secondary/20 p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
              Changes to be included
            </p>
            <div className="space-y-2 max-h-32 overflow-y-auto">
              {fixedFixes.map((fix, idx) => (
                <div
                  key={idx}
                  className="flex items-center gap-2 rounded-lg bg-background/50 px-3 py-2"
                >
                  <CheckCircle2 className="h-4 w-4 text-primary shrink-0" />
                  <code className="text-xs font-mono text-foreground flex-1 truncate">{fix.file}</code>
                  <Badge variant="outline" className="text-[9px] uppercase shrink-0">
                    {fix.bug_type}
                  </Badge>
                </div>
              ))}
            </div>
          </div>

          {/* Error Message */}
          {error && (
            <div className="flex items-center gap-2 rounded-lg bg-destructive/10 border border-destructive/20 px-3 py-2">
              <AlertCircle className="h-4 w-4 text-destructive shrink-0" />
              <p className="text-xs text-destructive">{error}</p>
            </div>
          )}

          {/* No GitHub Token Warning */}
          {!githubToken && (
            <div className="flex items-center gap-2 rounded-lg bg-amber-500/10 border border-amber-500/20 px-3 py-2">
              <AlertCircle className="h-4 w-4 text-amber-500 shrink-0" />
              <p className="text-xs text-amber-500">
                Sign in with GitHub to create a Pull Request
              </p>
            </div>
          )}
        </div>

        <AlertDialogFooter className="flex-col sm:flex-row gap-2">
          <AlertDialogCancel disabled={isCreating}>
            Cancel
          </AlertDialogCancel>
          <Button
            onClick={handleCreatePR}
            disabled={isCreating || !githubToken}
            className="gap-2"
          >
            {isCreating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Creating PR...
              </>
            ) : (
              <>
                <GitPullRequest className="h-4 w-4" />
                Create Pull Request
              </>
            )}
          </Button>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
